# Agenda
- Pandas
- Git

In [5]:
import pandas as pd

In [7]:
titanic_dataset_github_url_local =  "titanic.csv"
df = pd.read_csv(titanic_dataset_github_url_local)

In [8]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [13]:
df['Name_replaced'] =df['Name'].str.replace("Mr.","Sir",regex=False).head()
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Name_replaced
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,"Braund, Sir Owen Harris"
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,"Cumings, Mrs. John Bradley (Florence Briggs Th..."
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,"Heikkinen, Miss. Laina"
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,"Futrelle, Mrs. Jacques Heath (Lily May Peel)"
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,"Allen, Sir William Henry"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,NaN
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,NaN
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,NaN
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,NaN
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,NaN

In [10]:
df.loc[1]['Name']

'Cumings, Mrs. John Bradley (Florence Briggs Thayer)'

In [11]:
df.loc[1,'Name']

'Cumings, Mrs. John Bradley (Florence Briggs Thayer)'

In [16]:
start = df.loc[1,'Name'].find("(")

In [17]:
end = df.loc[1,'Name'].find(")")

In [19]:
df.loc[1,'Name'][0:start] + df.loc[1,'Name'][end:+1]

'Cumings, Mrs. John Bradley '

In [22]:
def remove_parentheses(text):
    if pd.isna(text):
        return text
    start = text.find("(")
    end = text.find(")")
    if start != -1 and end != +1 and end > start:
        return text[:start].rstrip()  # remove trailing space before '('
    return text

In [23]:
df["Name_clean"] = df["Name"].apply(remove_parentheses)
df[["Name", "Name_clean"]].head()

,Name,Name_clean
0,"Braund, Mr. Owen Harris","Braund, Mr. Owen Harris"
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...","Cumings, Mrs. John Bradley"
2,"Heikkinen, Miss. Laina","Heikkinen, Miss. Laina"
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)","Futrelle, Mrs. Jacques Heath"
4,"Allen, Mr. William Henry","Allen, Mr. William Henry"

In [24]:
def remove_brackets_part(name):
    if pd.isna(name):
        return name

    start = name.find("(")
    end = name.find(")")

    # if brackets not found properly, return as-is
    if start == -1 or end == -1 or end < start:
        return name

    # keep before '(' + keep after ')'
    cleaned = name[:start] + name[end+1:]
    return cleaned.strip()

In [26]:
df["Name_clean"] = df["Name"].apply(remove_brackets_part)
df[["Name", "Name_clean"]].head()

,Name,Name_clean
0,"Braund, Mr. Owen Harris","Braund, Mr. Owen Harris"
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...","Cumings, Mrs. John Bradley"
2,"Heikkinen, Miss. Laina","Heikkinen, Miss. Laina"
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)","Futrelle, Mrs. Jacques Heath"
4,"Allen, Mr. William Henry","Allen, Mr. William Henry"

In [29]:
# Replace substring with Regex : Regular expression

# * mans zero or more 
# . match any character 

# "\(.*\)"

df['Name_replaced'] =df['Name'].str.replace(r"\(.*\)","HELLO",regex=True)

In [31]:
df[['Name','Name_replaced']]

,Name,Name_replaced
0,"Braund, Mr. Owen Harris","Braund, Mr. Owen Harris"
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...","Cumings, Mrs. John Bradley HELLO"
2,"Heikkinen, Miss. Laina","Heikkinen, Miss. Laina"
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)","Futrelle, Mrs. Jacques Heath HELLO"
4,"Allen, Mr. William Henry","Allen, Mr. William Henry"
...,...,...
886,"Montvila, Rev. Juozas","Montvila, Rev. Juozas"
887,"Graham, Miss. Margaret Edith","Graham, Miss. Margaret Edith"
888,"Johnston, Miss. Catherine Helen ""Carrie""","Johnston, Miss. Catherine Helen ""Carrie"""
889,"Behr, Mr. Karl Howell","Behr, Mr. Karl Howell"
890,"Dooley, Mr. Patrick","Dooley, Mr. Patrick"

## Split and Access Elements

In [32]:
df['Name'][0]

'Braund, Mr. Owen Harris'

In [35]:
# df['Name'].str.split(",",expand=True)[0]
df['Name'].str.split(",")[0]

['Braund', ' Mr. Owen Harris']

In [36]:
df['Name'].str.split()[0]

['Braund,', 'Mr.', 'Owen', 'Harris']

In [37]:
df['Name'].str.split(",")[0][0]

'Braund'

In [40]:
df['Name'].str.split().str[0]

0         Braund,
1        Cumings,
2      Heikkinen,
3       Futrelle,
4          Allen,
          ...
886     Montvila,
887       Graham,
888     Johnston,
889         Behr,
890       Dooley,
Name: Name, Length: 891, dtype: object

## Strip Spaces

In [41]:
df['Name'].str.strip()

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

In [44]:
print(df['Name'].str.split()[0][0])

Braund,

## Find Position of Substring

In [45]:
df['Name'].str.find("Mr")

0       8
1       9
2      -1
3      10
4       7
       ..
886    -1
887    -1
888    -1
889     6
890     8
Name: Name, Length: 891, dtype: int64

In [47]:
count = df['Name'].str.contains("Miss").sum()
print("Number of 'Miss' : " , count)

Number of 'Miss' :  182

In [50]:
df['Name'].str.pad(width=50, side='left' ,fillchar ='-')

0      ---------------------------Braund, Mr. Owen Ha...
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2      ----------------------------Heikkinen, Miss. L...
3      ------Futrelle, Mrs. Jacques Heath (Lily May P...
4      --------------------------Allen, Mr. William H...
                             ...
886    -----------------------------Montvila, Rev. Ju...
887    ----------------------Graham, Miss. Margaret E...
888    ----------Johnston, Miss. Catherine Helen "Car...
889    -----------------------------Behr, Mr. Karl Ho...
890    -------------------------------Dooley, Mr. Pat...
Name: Name, Length: 891, dtype: str

# Categorical Data in Pandas
- What is Categorical Data ?
- Categorical data is textual or labeled data that represents dicrete categories

In [52]:
class_data = {
    "Name"   : ["A","B","C","D"],
    "Groups" : ["G1","G2","G3","G4"]
}

In [53]:
pd.DataFrame(class_data)

  Name Groups
0    A     G1
1    B     G2
2    C     G3
3    D     G4

In [54]:
class_df = pd.DataFrame(class_data)

In [ ]:
# df['Groups' ]> "G4" error

In [59]:
class_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      str
 1   Groups  4 non-null      str
dtypes: str(2)
memory usage: 196.0 bytes

In [ ]:
class_df['Group_Cat'] = pd.Categorical(
    class_df['Groups'],
    categories = ['G3','G1','G2','G4'],  # Custom order Higher to lower (Accending)
    ordered = True
)

In [61]:
class_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       4 non-null      str
 1   Groups     4 non-null      str
 2   Group_Cat  4 non-null      category
dtypes: category(1), str(2)
memory usage: 404.0 bytes

In [63]:
class_df['Group_Cat'].cat.categories

Index(['G3', 'G1', 'G2', 'G4'], dtype='str')

In [64]:
class_df["Group_Cat"]>"G4"

0    False
1    False
2    False
3    False
Name: Group_Cat, dtype: bool

In [65]:
class_df["Group_Cat"]>="G4"

0    False
1    False
2    False
3     True
Name: Group_Cat, dtype: bool

In [66]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Name_replaced,Name_clean
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,"Braund, Mr. Owen Harris","Braund, Mr. Owen Harris"
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,"Cumings, Mrs. John Bradley HELLO","Cumings, Mrs. John Bradley"
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,"Heikkinen, Miss. Laina","Heikkinen, Miss. Laina"
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,"Futrelle, Mrs. Jacques Heath HELLO","Futrelle, Mrs. Jacques Heath"
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,"Allen, Mr. William Henry","Allen, Mr. William Henry"

In [67]:
titanic_dataset_github_url_local =  "titanic.csv"
df = pd.read_csv(titanic_dataset_github_url_local)

In [68]:
df['Embarked'].unique()

<StringArray>
['S', 'C', 'Q', nan]
Length: 4, dtype: str

In [70]:
df['Embarked'] = df['Embarked'].fillna("N")

In [71]:
df['Embarked'].unique()

<StringArray>
['S', 'C', 'Q', 'N']
Length: 4, dtype: str

In [73]:
df['Embarked_auto_cat'] = df['Embarked'].astype('category')

In [74]:
df['Embarked_auto_cat'].cat.categories

Index(['C', 'N', 'Q', 'S'], dtype='str')

In [76]:
df['Embarked_cust_cat'] = pd.Categorical(
    df['Embarked'],
    categories = ['N','S','C','Q'],  # Custom order Higher to lower (Accending)
    ordered = True
)

In [77]:
df['Embarked_cust_cat'].cat.categories

Index(['N', 'S', 'C', 'Q'], dtype='str')

In [78]:
df['Embarked_cust_cat']>'S'

0      False
1       True
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889     True
890     True
Name: Embarked_cust_cat, Length: 891, dtype: bool

In [79]:
df['Embarked_cust_cat'].head()

0    S
1    C
2    S
3    S
4    S
Name: Embarked_cust_cat, dtype: category
Categories (4, str): ['N' < 'S' < 'C' < 'Q']

In [80]:
df['Embarked_cust_cat'].cat.codes.head()

0    1
1    2
2    1
3    1
4    1
dtype: int8

In [ ]:
df['Sex'].unique()

# i want to convert the values of Sex column and encode them in 0 & 1

<StringArray>
['male', 'female']
Length: 2, dtype: str

In [ ]:
df["Sex_encoded"] = pd.Categorical(df["Sex"], categories=["male", "female"]).codes

In [ ]:
df[["Sex", "Sex_encoded"]].head()

      Sex  Sex_encoded
0    male            0
1  female            1
2  female            1
3  female            1
4    male            0

# Date Functionality in Pandas

In [85]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   PassengerId        891 non-null    int64
 1   Survived           891 non-null    int64
 2   Pclass             891 non-null    int64
 3   Name               891 non-null    str
 4   Sex                891 non-null    str
 5   Age                714 non-null    float64
 6   SibSp              891 non-null    int64
 7   Parch              891 non-null    int64
 8   Ticket             891 non-null    str
 9   Fare               891 non-null    float64
 10  Cabin              204 non-null    str
 11  Embarked           891 non-null    str
 12  Embarked_auto_at   891 non-null    category
 13  Embarked_auto_cat  891 non-null    category
 14  Embarked_cust_cat  891 non-null    category
 15  Sex_encoded        891 non-null    int8
dtypes: category(3), float64(2), int64(5), int8(1), str(5)
memory usage: 87.4 KB

 # Git (Code version control tool)
 - tools to manage code
 - uv  project + dependencies
 - GitHub -> Central repository of your code +  git
 - Github is platoform which uses git tool